# Site settings
title: Niels Oeltjen Folio
description: Niels Oeltjen Folio
url: elbone.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

# Increment to bust cache
version: 1
